# Generated by Django 4.1.7 on 2023-02-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deviceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='cpu_temp',
            field=models.IntegerField(null=True),
        ),
    ]
