# Generated by Django 4.1.7 on 2023-02-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_deviceinfo_cpu_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='cpu_load',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='disk_usage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='memory_usage',
            field=models.FloatField(null=True),
        ),
    ]
