# Generated by Django 4.1.7 on 2023-03-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_deviceinfo_cpu_load_deviceinfo_disk_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='ip_address',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
